---
- name: liab/bird1 | install bird
  yum:
    name: bird
    state: present

- name: liab/bird1 | template bird conf
  template:
    src: bird.conf.j2
    dest: /etc/bird.conf
    owner: root
    group: bird
    mode: 0640
  notify: restart bird

- name: liab/bird1 | systemd
  systemd:
    name: bird
    state: started
    enabled: yes

- name: liab/bird1 | flush handlers
  meta: flush_handlers
