---
# Not using nmcli module because it is preview at the time of writing.
# Doing it the hard-way also makes it so I actually learn nmcli.

- name: liab/networking | mktemp
  command: mktemp -d
  register: _mktemp

- block:
  - name: liab/networking | check if we have our bridge interface
    command: "nmcli dev show {{ item.key }}"
    with_dict: "{{ networks }}"
    register: _bridges
    ignore_errors: yes

  - name: liab/networking | create bridge networks
    command: "nmcli connection add ifname {{ item.item.key }} type bridge con-name {{ item.item.key }}"
    with_items: "{{ _bridges.results }}"
    when: "item.rc != 0"

  - name: liab/networking | wait for connections to be created
    command: "nmcli connection show {{ item.item.key }}"
    with_items: "{{ _bridges.results }}"
    register: _wait_for
    when: item.rc != 0
    retries: 5
    delay: 2
    until: "_wait_for.rc == 0"

  - name: liab/networking | make relevant connection changes
    command: "nmcli connection modify {{ item[0].item.key }} {{ item[1] }}"
    with_nested:
    - "{{ _bridges.results }}"
    - - "ipv4.method disabled"
      - "ipv6.method ignore"
      - "802-3-ethernet.mtu 9000"
    when: "item[0].rc != 0"

  # Apparently NetworkManager requires ifdown/up or restart NetworkManager to make connection changes take effect
  - name: liab/networking | bounce the connection
    command: "nmcli connection {{ item[1] }} {{ item[0].item.key }}"
    with_nested:
    - "{{ _bridges.results }}"
    - - "down"
      - "up"
    when: "item[0].rc != 0"

  # NetworkManager does not support veth, so we have to do it by hand
  # Not sure how to send a notify using variables in the name
  - name: liab/networking | create the veth systemd units
    template:
      src: systemd-veth.service.j2
      dest: "/etc/systemd/system/veth-{{ item.key }}.service"
      owner: root
      group: root
      mode: 0644
    with_dict: "{{ networks }}"
    when: '"routing" in item.key'
    register: _systemd_veth

  - name: liab/networking | restart veths
    systemd:
      name: "veth-{{ item.item.key }}"
      state: restarted
      enabled: yes
      daemon_reload: yes
    with_items: "{{ _systemd_veth.results }}"
    when: "item.changed"

  - name: liab/networking | enable and start veth systemd
    systemd:
      name: "veth-{{ item.item.key }}"
      state: started
      enabled: yes
      daemon_reload: yes
    with_items: "{{ _systemd_veth.results }}"
    when: '"routing" in item.item.key'
 
  - name: liab/networking | check for libvirt network
    shell: "virsh net-list --all --name | grep {{ item.key }}"
    register: _libvirt_networks
    with_dict: "{{ networks }}"
    ignore_errors: yes

  - name: liab/networking | template out libvirt networks
    template:
      src: libvirt-network.xml.j2
      dest: "{{ _mktemp.stdout }}/libvirt-network-{{ item.item.key }}.xml"
    with_items: "{{ _libvirt_networks.results }}"
    when: "item.rc != 0"

  - name: liab/networking | create libvirt networks
    command: "virsh net-define {{ _mktemp.stdout }}/libvirt-network-{{ item.item.key }}.xml"
    with_items: "{{ _libvirt_networks.results }}"
    when: "item.rc != 0"

  - name: liab/networking | modify libvirt networks
    command: "virsh {{ item[1] }} {{ item[0].item.key }}"
    with_nested:
    - "{{ _libvirt_networks.results }}"
    - - "net-start"
      - "net-autostart"
    when: "item[0].rc != 0"

  always:
  - name: liab/networking | cleanup
    file:
      path: "{{ _mktemp.stdout }}"
      state: absent
