---
- name: epel | epel7
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  when: 'ansible_distribution_major_version == "7"'

- name: epel | epel8
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
  when: 'ansible_distribution_major_version == "8"'
