---
lab_domain_name: lab.dchin.dev
lab_host_bgp_asn: 65000
lab_mac_prefix: "1a:b0"
lab_machines:
  lab1:
    network: 192.168.254.0/24
    peering_network: 192.168.255.254/31
    bgp_asn: 65001
    machines:
      master1:
        cpu: 1
        memory: 768
        ip: 192.168.254.10
        disks:
        - name: vda
          size: 32
        type: machine
#      esxi1:
#        cpu: 2
#        memory: 4096
#        ip: 192.168.254.11
#        disks:
#        - name: vda
#          size: 64
#        type: esxi
  lab2:
    network: 192.168.253.0/24
    peering_network: 192.168.255.252/31
    bgp_asn: 65002
    machines:
      master2:
        cpu: 1
        memory: 768
        ip: 192.168.253.10
        disks:
        - name: vda
          size: 32
        type: machine
#      esxi2:
#        cpu: 2
#        memory: 4096
#        ip: 192.168.253.11
#        disks:
#        - name: vda
#          size: 64
#        type: esxi
  lab3:
    network: 192.168.252.0/24
    peering_network: 192.168.255.250/31
    bgp_asn: 65003
    machines:
      master3:
        cpu: 1
        memory: 768
        ip: 192.168.252.10
        disks:
        - name: vda
          size: 32
        type: machine
#      esxi3:
#        cpu: 2
#        memory: 4096
#        ip: 192.168.252.11
#        disks:
#        - name: vda
#          size: 64
#        type: esxi

lab_public_ssh_key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHYU5ohkrcI9PZHZZTFWkhlKfCfp5rsEslWDyzz3w3hYzec/fOiP92M29Ck/JS35N1BZ+vZZ7JOqjxmXhADt6V8='
